services:
  nginx:
    image: nginx:1.25-alpine
    container_name: verify_email_nginx
    restart: unless-stopped
    ports:
      - "8280:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - verify_email_network

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: verify_email_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - verify_email_network

networks:
  verify_email_network:
    driver: bridge